name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry --version
          poetry config virtualenvs.in-project true
          poetry install

      - name: Quality
        run: |
          poetry run black -l 79 --check micebot

      - name: Testing and code coverage
        run: |
          poetry run coverage run -m unittest discover -s test/unit -v
          poetry run coverage report
