name: Python application test heroku

on:
  push:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pip
      run: python -m pip install --upgrade pip
  
    - name: Install poetry
      run: pip install poetry
        
    - name: Install dependencies project
      run: poetry install
        
    - name: Poetry config virtualenvs
      run: poetry config virtualenvs.in-project true
        
    - name: Run pylama
      run: poetry run pylama micebot
